### ISSUE TITLE
Published with a typo

### ISSUE THREAD

**Issue by nikolay** [carlnordenfelt/lulo-plugin-amazon-inspector-role#1]
The NPM module is missing a `c`: `lulo-plugin-amazon-inspetor-role`!

Please, fix and republish!

**Comment by nikolay** [comment]
https://github.com/carlnordenfelt/lulo-plugin-amazon-inspector-role/blob/master/package.json#L2

**Comment by carlnordenfelt** [comment]
Thanks!

New package available at lulo-plugin-amazon-inspector-role@2.0.0

**Comment by nikolay** [comment]
@carlnordenfelt You need to unpublish the old one: https://www.npmjs.com/package/lulo-plugin-amazon-inspetor-role

**Comment by carlnordenfelt** [comment]
I won't unpublish as there might be projects that depend on it. I have deprecated it though.
